import os
import json
import subprocess

# Purane YouTube links (Inhe mat chhedna)
fixed_content = {
    "tutorials": ["ScMzIvxBSi4", "5QrR9PZW_BI"],
    "shorts": ["uCWigClzovY", "YRaIypeXVcY"],
    "pastLives": ["ScMzIvxBSi4"],
    "playlists": ["UURfvXfU4toossqCIbuXNblA"]
}

# Main folders ki list
folders = {
    "pdfs": "files/pdfs",
    "ppts": "files/ppts",
    "images": "files/images",
    "codes": "files/codes",
    "others": "files/others"
}

# Sabhi files ko store karne ke liye empty lists
data = {"pdfs": [], "ppts": [], "images": [], "codes": [], "others": []}

# Har folder ko scan karna
for category, path in folders.items():
    if os.path.exists(path):
        for filename in os.listdir(path):
            # Sirf asli files uthana (hidden files nahi)
            if not filename.startswith('.'):
                filepath = f"{path}/{filename}"
                title = os.path.splitext(filename)[0].replace('-', ' ').title()
                data[category].append({"title": title, "link": filepath})

# videos.js taiyar karna
js_code = f"""// AUTO-GENERATED BY ASIF TECH AUTOMATION
const myContent = {{
    tutorials: {json.dumps(fixed_content['tutorials'])},
    shorts: {json.dumps(fixed_content['shorts'])},
    pastLives: {json.dumps(fixed_content['pastLives'])},
    
    pdfs: {json.dumps(data['pdfs'], indent=4)},
    ppts: {json.dumps(data['ppts'], indent=4)},
    images: {json.dumps(data['images'], indent=4)},
    codes: {json.dumps(data['codes'], indent=4)},
    others: {json.dumps(data['others'], indent=4)},
    
    playlists: {json.dumps(fixed_content['playlists'])}
}};
"""

# Save videos.js
with open('videos.js', 'w') as f:
    f.write(js_code)

# GitHub Push
subprocess.run(["git", "add", "."])
subprocess.run(["git", "commit", "-m", "Auto-sync folders updated"])
subprocess.run(["git", "push"])
print("🚀 Website updated successfully from sub-folders!")