import os
import json
import subprocess

# Aapke purane YouTube links yahan fix rahenge
fixed_content = {
    "tutorials": ["ScMzIvxBSi4", "5QrR9PZW_BI"],
    "shorts": ["uCWigClzovY", "YRaIypeXVcY"],
    "pastLives": ["ScMzIvxBSi4"],
    "playlists": ["UURfvXfU4toossqCIbuXNblA"]
}

files_dir = 'files'
pdfs, ppts, images = [], [], []

# Folder scan karna aur files ko unke extension ke hisaab se baantna
if os.path.exists(files_dir):
    for filename in os.listdir(files_dir):
        filepath = f"files/{filename}"
        title = os.path.splitext(filename)[0].replace('-', ' ').title()
        item = {"title": title, "link": filepath}
        
        ext = filename.lower()
        if ext.endswith('.pdf'):
            pdfs.append(item)
        elif ext.endswith(('.ppt', '.pptx')):
            ppts.append(item)
        elif ext.endswith(('.jpg', '.jpeg', '.png', '.gif')):
            images.append(item)

# Naya videos.js ka code taiyar karna
js_code = f"""// AUTO-GENERATED BY PYTHON SCRIPT
const myContent = {{
    tutorials: {json.dumps(fixed_content['tutorials'])},
    shorts: {json.dumps(fixed_content['shorts'])},
    pastLives: {json.dumps(fixed_content['pastLives'])},
    
    pdfs: {json.dumps(pdfs, indent=4)},
    ppts: {json.dumps(ppts, indent=4)},
    images: {json.dumps(images, indent=4)},
    
    playlists: {json.dumps(fixed_content['playlists'])}
}};
"""

# videos.js ko khud update karna
with open('videos.js', 'w') as f:
    f.write(js_code)
print("✅ videos.js automatically update ho gayi!")

# GitHub par khud push karna
subprocess.run(["git", "add", "."])
subprocess.run(["git", "commit", "-m", "Auto-uploaded files via Python script"])
subprocess.run(["git", "push"])
print("🚀 Website par successfully live ho gaya!")