import os
import json
import subprocess

# Purane YouTube links (Inhe mat chhedna)
fixed_content = {
    "tutorials": ["ScMzIvxBSi4", "5QrR9PZW_BI"],
    "shorts": ["uCWigClzovY", "YRaIypeXVcY"],
    "pastLives": ["ScMzIvxBSi4"],
    "playlists": ["UURfvXfU4toossqCIbuXNblA"]
}

# Main folders ki list
folders = {
    "pdfs": "files/pdfs",
    "ppts": "files/ppts",
    "images": "files/images",
    "codes": "files/codes",
    "others": "files/others"
}

# Sabhi files ko store karne ke liye empty lists
data = {"pdfs": [], "ppts": [], "images": [], "codes": [], "others": []}

# Har folder ko scan karna
for category, path in folders.items():
    if os.path.exists(path):
        for filename in os.listdir(path):
            # Sirf asli files uthana (hidden files nahi)
            if not filename.startswith('.'):
                filepath = f"{path}/{filename}"
                title = os.path.splitext(filename)[0].replace('-', ' ').title()
                data[category].append({"title": title, "link": filepath})

# videos.js taiyar karna
js_code = f"""// AUTO-GENERATED BY ASIF TECH AUTOMATION
const myContent = {{
    tutorials: {json.dumps(fixed_content['tutorials'])},
    shorts: {json.dumps(fixed_content['shorts'])},
    pastLives: {json.dumps(fixed_content['pastLives'])},
    
    pdfs: {json.dumps(data['pdfs'], indent=4)},
    ppts: {json.dumps(data['ppts'], indent=4)},
    images: {json.dumps(data['images'], indent=4)},
    codes: {json.dumps(data['codes'], indent=4)},
    others: {json.dumps(data['others'], indent=4)},
    
    playlists: {json.dumps(fixed_content['playlists'])}
}};
"""

# Save videos.js
with open('videos.js', 'w') as f:
    f.write(js_code)

# GitHub Push
subprocess.run(["git", "add", "."])
subprocess.run(["git", "commit", "-m", "Auto-sync folders updated"])
subprocess.run(["git", "push"])
print("🚀 Website updated successfully from sub-folders!")
import os
import json

# Aapke folders ki location
CODE_DIR = "codes"
OUTPUT_FILE = "codes.js"

def sync_codes_to_js():
    premium_scripts = []
    
    # codes folder ke andar se saari files uthana
    if os.path.exists(CODE_DIR):
        for filename in os.listdir(CODE_DIR):
            filepath = os.path.join(CODE_DIR, filename)
            if os.path.isfile(filepath):
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                    premium_scripts.append({
                        "name": filename,
                        "content": content,
                        "ext": filename.split('.')[-1]
                    })
    
    # codes.js file banana taaki website ise padh sake
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(f"const myPremiumScripts = {json.dumps(premium_scripts)};")
    print(f"✅ Synced {len(premium_scripts)} scripts to codes.js")

# Ise call karein
sync_codes_to_js()