// AUTO-GENERATED BY PYTHON SCRIPT
const myContent = {
    tutorials: ["ScMzIvxBSi4", "5QrR9PZW_BI"],
    shorts: ["uCWigClzovY", "YRaIypeXVcY"],
    pastLives: ["ScMzIvxBSi4"],
    
    pdfs: [],
    ppts: [],
    images: [],
    
    playlists: ["UURfvXfU4toossqCIbuXNblA"]
};
