// AUTO-GENERATED BY ASIF TECH AUTOMATION
const myContent = {
    tutorials: ["ScMzIvxBSi4", "5QrR9PZW_BI"],
    shorts: ["uCWigClzovY", "YRaIypeXVcY"],
    pastLives: ["ScMzIvxBSi4"],
    
    pdfs: [],
    ppts: [],
    images: [],
    codes: [
    {
        "title": "Ppt Codeing",
        "link": "files/codes/ppt codeing"
    }
],
    others: [],
    
    playlists: ["UURfvXfU4toossqCIbuXNblA"]
};
