// AUTO-GENERATED BY PYTHON SCRIPT
const myContent = {
    tutorials: ["ScMzIvxBSi4", "5QrR9PZW_BI"],
    shorts: ["uCWigClzovY", "YRaIypeXVcY"],
    pastLives: ["ScMzIvxBSi4"],
    
    pdfs: [
    {
        "title": "Asif",
        "link": "files/ASIF.pdf"
    }
],
    ppts: [
    {
        "title": "You Tube",
        "link": "files/you tube.pptx"
    }
],
    images: [
    {
        "title": "Asif",
        "link": "files/asif.png"
    }
],
    
    playlists: ["UURfvXfU4toossqCIbuXNblA"]
};
